const countryList = {
    AED: { country: "United Arab Emirates", symbol: "د.إ" },
    AFN: { country: "Afghanistan", symbol: "؋" },
    XCD: { country: "Eastern Caribbean Dollar", symbol: "$" },
    ALL: { country: "Albania", symbol: "Lek" },
    AMD: { country: "Armenia", symbol: "֏" },
    ANG: { country: "Netherlands Antilles", symbol: "ƒ" },
    AOA: { country: "Angola", symbol: "Kz" },
    ARS: { country: "Argentina", symbol: "$" },
    AUD: { country: "Australia", symbol: "$" },
    AZN: { country: "Azerbaijan", symbol: "₼" },
    BAM: { country: "Bosnia and Herzegovina", symbol: "KM" },
    BBD: { country: "Barbados", symbol: "$" },
    BDT: { country: "Bangladesh", symbol: "৳" },
    BGN: { country: "Bulgaria", symbol: "лв" },
    BHD: { country: "Bahrain", symbol: ".د.ب" },
    BIF: { country: "Burundi", symbol: "Fr" },
    BMD: { country: "Bermuda", symbol: "$" },
    BRL: { country: "Brazil", symbol: "R$" },
    CAD: { country: "Canada", symbol: "$" },
    CHF: { country: "Switzerland", symbol: "Fr" },
    CNY: { country: "China", symbol: "¥" },
    COP: { country: "Colombia", symbol: "$" },
    CZK: { country: "Czech Republic", symbol: "Kč" },
    DKK: { country: "Denmark", symbol: "kr" },
    DOP: { country: "Dominican Republic", symbol: "$" },
    EGP: { country: "Egypt", symbol: "ج.م" },
    EUR: { country: "Eurozone", symbol: "€" },
    GBP: { country: "United Kingdom", symbol: "£" },
    HKD: { country: "Hong Kong", symbol: "$" },
    INR: { country: "India", symbol: "₹" },
    JPY: { country: "Japan", symbol: "¥" },
    KRW: { country: "South Korea", symbol: "₩" },
    MXN: { country: "Mexico", symbol: "$" },
    MYR: { country: "Malaysia", symbol: "RM" },
    NGN: { country: "Nigeria", symbol: "₦" },
    NOK: { country: "Norway", symbol: "kr" },
    NZD: { country: "New Zealand", symbol: "$" },
    PHP: { country: "Philippines", symbol: "₱" },
    PKR: { country: "Pakistan", symbol: "₨" },
    PLN: { country: "Poland", symbol: "zł" },
    QAR: { country: "Qatar", symbol: "ر.ق" },
    RUB: { country: "Russia", symbol: "₽" },
    SAR: { country: "Saudi Arabia", symbol: "ر.س" },
    SEK: { country: "Sweden", symbol: "kr" },
    SGD: { country: "Singapore", symbol: "$" },
    THB: { country: "Thailand", symbol: "฿" },
    TRY: { country: "Turkey", symbol: "₺" },
    TWD: { country: "Taiwan", symbol: "NT$" },
    USD: { country: "United States", symbol: "$" },
    UYU: { country: "Uruguay", symbol: "$" },
    VND: { country: "Vietnam", symbol: "₫" },
    ZAR: { country: "South Africa", symbol: "R" },
};
